//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomCollectionApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfEmployee xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <Employee>
    <FirstName>John</FirstName>
    <LastName>Doe</LastName>
    <DateOfHire>2008-03-13T00:00:00</DateOfHire>
  </Employee>
  <Employee>
    <FirstName>Jane</FirstName>
    <LastName>Doe</LastName>
    <DateOfHire>2008-03-01T00:00:00</DateOfHire>
  </Employee>
</ArrayOfEmployee>")]
        public global::Organization.EmployeeCollection Employees {
            get {
                return ((global::Organization.EmployeeCollection)(this["Employees"]));
            }
            set {
                this["Employees"] = value;
            }
        }
    }
}
